source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'KeyReply_Example' do
#  pod 'KeyReply', :path => "../"

  target 'KeyReply_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'Expecta+Snapshots'
  end

end
