use_frameworks!

target 'KeyReply_Example' do
  pod 'KeyReply', :path => '../'

  target 'KeyReply_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
